abstract: Can't insert and update for DBIC
author: Atsushi Kobayashi  C<< <atsushi __at__ mobilefactory.jp> >>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: DBIx-Class-StorageReadOnly
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp::Clan: 0
  DBIx::Class: 0
version: 0.01
